name: Reusable Ubuntu Build Workflow
on:
  workflow_call:
    inputs:
      target:
        description: "Target to be built"
        required: true
        type: "string"
      build_type:
          description: "Build type"
          type: "string"
          default: "Release"
jobs:
  Configuration:
    runs-on: ubuntu-latest
    container:
      image: duyleduc520/mysfmlapp:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          args: |
            --graphviz=$PWD/docs/graph/graph.dot
            --no-warn-unused-cli
            -DCMAKE_BUILD_TYPE=${{inputs.build_type}}
            -DDOCS_DIR=$PWD/docs
            -DCMAKE_INSTALL_PREFIX=$PWD/install
          build-args: |
            --target=${{inputs.target}}
            --config=${{inputs.build_type}}
    