name: Reusable Ubuntu Build Workflow
on:
  workflow_call:
    inputs:
      target:
        description: "Target to be built"
        required: true
        type: "string"
        default: "complete"
jobs:
  Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: update & install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y cmake
          sudo apt-get install -y git doxygen
          sudo apt-get install -y python3 python3-pip
          sudo apt-get install -y ninja-build
          sudo apt-get install -y graphviz pkg-config
          sudo apt-get install -y dos2unix
          sudo apt-get install -y cmake-format
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: make config-ubuntu
      - name: Build
        run: cmake --build --preset=ubuntu-${{inputs.target}}
    