name: Reusable Ubuntu Build Workflow
on:
  workflow_call:
    inputs:
      target:
        description: "Target to be built"
        required: true
        type: "string"
      build_type:
          description: "Build type"
          type: "string"
          default: "Release"
jobs:
  Configuration:
    runs-on: windows-latest
    steps:
      - name: Install dependencies by choco
        run: choco install graphviz ninja make dos2unix doxygen.portable
      - name: install cmake-format
        run: |
          pip install cmake-format
          pip install PyYAML
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get cpu amount
        id: cpu
        run: |
          echo "count=$(nproc)" >> $GITHUB_OUTPUT
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          build-dir: out/build/msvc
          args: |
            --graphviz=./docs/graph/graph.dot
            --no-warn-unused-cli
            --preset=msvc
          options: |
            CMAKE_BUILD_TYPE=${{inputs.build_type}}
          build-args: |
            -j${{steps.cpu.outputs.count}}
            --target=ALL_BUILD
            --config=${{inputs.build_type}}
      - name: Installation
        run: cmake --build ./out/build/msvc -j${{steps.cpu.outputs.count}} --target=INSTALL --config=${{inputs.build_type}}
