name: Reusable Build Workflow
on:
  workflow_call:
    inputs:
      target:
        description: "Target to be built"
        required: true
        type: "string"
      build_type:
        description: "Build type"
        type: "string"
        default: "Release"
      os:
        description: "Operating system"
        required: true
        type: "string"
jobs:
  build-ubuntu:
    if: ${{inputs.os == 'ubuntu'}}
    uses: ./.github/workflows/build-ubuntu.yml
    with:
      target: ${{inputs.target}}
      build_type: ${{inputs.build_type}}
  build-windows:
    if: ${{inputs.os == 'windows'}}
    uses: ./.github/workflows/build-windows.yml
    with:
      target: ${{inputs.target}}