name: Reusable Ubuntu Build Workflow
on:
  workflow_call:
    inputs:
      target:
        description: "Target to be built"
        required: true
        type: "string"
      build_type:
          description: "Build type"
          type: "string"
          default: "Release"
jobs:
  Configuration:
    runs-on: windows-latest
    steps:
      - name: install graphviz
        run: choco install graphviz
      - name: install ninja
        run: choco install ninja
      - name: install make
        run: choco install make
      - name: install dos2unix
        run: choco install dos2unix
      - name: install doxygen
        run: choco install doxygen.portable
      - name: install cmake-format
        run: |
          pip install cmake-format
          pip install PyYAML
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get cpu amount
        id: cpu
        run: |
          echo "count=$(nproc)" >> $GITHUB_OUTPUT
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          build-dir: out/build/ubuntu
          args: |
            --graphviz=./docs/graph/graph.dot
            --no-warn-unused-cli
            --preset=ubuntu
          options: |
            CMAKE_BUILD_TYPE=${{inputs.build_type}}
          build-args: |
            -j${{steps.cpu.outputs.count}}
            --target=${{inputs.target}}
            --config=${{inputs.build_type}}
      - name: Installation
        run: cmake --build ./out/build/ubuntu -j${{steps.cpu.outputs.count}} --target=install --config=${{inputs.build_type}}
