name: C/C++ CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install_essentail_deps
      run: sudo apt install -y build-essential python3 cmake doxygen graphviz ninja-build pkgconf 
    - name: install_gcc_deps
      run: sudo apt install libmpfr-dev libgmp3-dev libmpc-dev -y
    - name: install_cmake_format
      run: pip install cmake-format
    - name: git_config
      run: git config --global user.name "leducduy520"; git config --global user.email duyleduc123@gmail.com
    - name:  git_clone
      run: git clone -v --progress https://github.com/leducduy520/project-template.git
    - name: go_to_project-template
      run: cd project-template
    - name: run_configuration
      run: cmake --preset=u-ninja-gcc
    
      
