name: C/C++ CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: update & install deps
        run: |
          sudo apt update
          sudo apt-get upgrade
          sudo apt-get install gcc g++ gdb
          sudo apt-get install make cmake
          sudo apt-get install git doxygen
          sudo apt-get install python3 python3-pip
          pip install cmake-format
          pip install ninja
          sudo apt-get install graphviz pkg-config
      - name: git_config
        run: |
          git config --global user.name "leducduy520"
          git config --global user.email duyleduc123@gmail.com
      - name: git_clone
        run: git clone -v --progress https://github.com/leducduy520/project-template.git
      - name: go_to_project-template
        run: |
          cd project-template
          ls
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PWD/install/share/pkgconfig
          git branch; cmake --preset=u-ninja-gcc
