name: C/C++ CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install_essentail_deps
      run: sudo apt install -y build-essential python3 cmake doxygen graphviz ninja-build pkgconf 
    - name: install_gcc_deps
      run: sudo apt install libmpfr-dev libgmp3-dev libmpc-dev -y
    - name: install_cmake_format
      run: pip install cmake-format
    - name: test_cmake_vers
      run: cmake --version
    - name: check_folder
      run: ls;ls ..
      
