name: Input Example
on: 
  workflow_dispatch:
    inputs:
      hello:
        description: "Input a name"
        required: true
        default: "duyld"
        type: string
      enable_print:
        description: "Enable show point"
        required: true
        type: boolean
      amount:
        description: "A dumb number"
        required: false
        type: number
      work_environment:
        description: "Additional informations for printing"
        required: false
        type: environment
        
jobs:
  Print-Output:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs.hello
        run: echo ${{ inputs.hello }}
      - name: Print inputs.enable_print
        run: echo ${{ inputs.enable_print }}
      - name: Print inputs.amount
        run: echo ${{ inputs.amount }}
      - name: Print inputs.work_environment
        run: echo ${{ inputs.work_environment }}