name: Main test
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target to be built"
        required: false
        type: "string"
        default: "complete"
  push:
    branches:
      - main
    paths:
      - "**.c"
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "./Makefile"
      - "**/CMakePresets.json"
      - "**.py"
      - ".github/workflows/main.yml"
jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu]
        build_type: [release, debug]
    uses: ./.github/workflows/build.yml
    with:
      target: ${{inputs.target}}
      build_type: ${{matrix.build_type}}
      os: ${{matrix.os}}
    # runs-on: ubuntu-22.04
    # permissions:
    #   contents: write
    # steps:
    #   - name: build project
    #     uses: ./.github/workflows/reusable-ubuntu.yml
    #     with:
    #       target: ${{inputs.target}}
    #   - name: Upload artifact
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: app
    #       path: out/install/ubuntu
    #   - name: Deloy GitHub Page
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./docs/html
