name: Test
on: 
  push:
    branches:
      - main
jobs:
  job-one:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++
      - name: test folder
        run: ls
        
