name: Test project on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - merge-*
    paths:
      - "**.c"
      - "**.cpp"
      - "**.hpp"
      - "**.h"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "./Makefile"
      - "**/CMakePresets.json"
      - "**.py"
      - ".github/workflows/main.yml"
jobs:
  configure-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: update & install deps
        run: |
          sudo apt-get install gcc g++ gdb
          sudo apt-get install make cmake
          sudo apt-get install git doxygen
          sudo apt-get install python3 python3-pip
          pip install cmake-format
          pip install ninja
          sudo apt-get install graphviz pkg-config
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Configure Project
        id: config
        run: make config-ubuntu
      - name: Build Project
        id: build
        continue-on-error: true
        run: cmake --build --preset=ubuntu
      - name: Format cmake files
        run: cmake --build --preset=ubuntu-format
      - name: Generating docs
        id: docs_gen
        if: ${{!cancelled()}} && ${{steps.config.conclusion.success}}
        run: cmake --build --preset=ubuntu-docs
      - name: Installing project
        id: install
        if: ${{steps.build.outcome.success}}
        run: |
          cmake --build --preset=ubuntu-install
          echo "install_success=1" >> "$GITHUB_OUTPUT"
      - name: Authen and Execution
        if: ${{steps.install.outputs.install_success}} == 1
        run: |
          cd out/install/ubuntu/bin
          chmod a+x app Catch-test
          export LD_LIBRARY_PATH=$PWD/../lib
          ./Catch-test
          ./app
