name: Outputs test
on:
  workflow_dispatch:
jobs:
  Publish_output:
    runs-on: ubuntu-latest
    env:
      EVENT_DETAIL: ${{toJson(github.event)}}
    outputs:
      tool_files: ${{steps.publish.outputs.tool_files}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Publish
        id: publish
        run: find cmake/*.cmake -type f -exec echo 'tool_files={}' >> $GITHUB_OUTPUT ';'
      - name: print Github
        run: |
          echo "${{toJson(github)}}"
      - name: Check event
        run: |
          echo "$EVENT_DETAIL"
  Express_ouput:
    runs-on: ubuntu-latest
    if: ${{github.event.sender.login}} == "leducduy520"
    needs: Publish_output
    steps:
      - name: Print
        run: echo 'tool files are ${{needs.Publish_output.outputs.tool_files}}'
