name: Outputs test
on:
  workflow_dispatch:
env:
  WORKFLOW_ENV: duyleduc520
jobs:
  Create-Output:
    runs-on: ubuntu-latest
    outputs:
      duylove: ${{steps.save.outputs.mylove}}
    steps:
      - name: save value to output
        id: save
        run: echo "mylove=A" >> $GITHUB_OUTPUT
  Read-Output:
    runs-on: ubuntu-latest
    needs: Create-Output
    steps:
      - name: print previous job's output value
        run: echo "Duy's love is ${{needs.Create-Output.outputs.duylove}}"
  Read-Secret-Env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: tta_in_my_heart
    steps:
      - name: Print DUY_SECRET_NAME
        run: echo "${{secrets.DUY_SECRET_NAME}}"
      - name: Print workflow env var
        run: echo "${{env.WORKFLOW_ENV}}"
      - name: Print job env var
        run: echo "${{env.JOB_ENV}}"
