name: Outputs test
on:
  workflow_dispatch:
jobs:
  Publish_output:
    runs-on: ubuntu-latest
    outputs:
      tool_files: ${{steps.publish.outputs.tool_files}}
    env:
      EVENT_NAME: ${{ github.event_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Publish
        id: publish
        run: find cmake/*.cmake -type f -exec echo 'tool_files={}' >> $GITHUB_OUTPUT ';'
      - name: Check event
        run: |
          echo "$EVENT_NAME"
          echo "${{ github.event_name }}"
  Express_ouput:
    runs-on: ubuntu-latest
    needs: Publish_output
    steps:
      - name: Print
        run: echo 'tool files are ${{needs.Publish_output.outputs.tool_files}}'
