name: Outputs test
on:
  workflow_dispatch:
jobs:
  Create-Output:
    runs-on: ubuntu-latest
    outputs:
      duylove: ${{steps.save.outputs.mylove}}
    steps:
      - name: save value to output
        id: save
        run: echo "mylove=A" >> $GITHUB_OUTPUT
  Read-Output:
    runs-on: ubuntu-latest
    needs: Create-Output
    steps:
      - name: print previous job's output value
        run: echo "Duy's love is ${{needs.Create-Output.outputs.duylove}}"
