name: Test on Ubuntu
on:
  workflow_dispatch:
jobs:
  Configuration:
    runs-on: ubuntu-latest
    container:
      image: duyleduc520/mysfmlapp:latest
    steps:
      - uses: ./.github/actions/build/action.yml
        with:
          preset: ubuntu
        