name: Test on Ubuntu
on:
  workflow_dispatch:
jobs:
  Configuration:
    runs-on: ubuntu-latest
    container:
      image: duyleduc520/mysfmlapp:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build project
        env:
          MONGODB_NAME: ${{ vars.MONGODB_NAME}}
          MONGODB_COLL: ${{ vars.MONGODB_COLL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        uses: ./.github/actions/build
        with:
          preset: ubuntu
        