name: Test on Ubuntu
on:
  workflow_dispatch:
jobs:
  Configuration:
    runs-on: ubuntu-latest
    container:
      image: duyleduc520/mysfmlapp:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          args: |
            --graphviz=docs/graph/graph.dot
            --no-warn-unused-cli
            --preset=ubuntu
          build-args: |
            --preset=ubuntu
