name: Test on Ubuntu
on:
  workflow_dispatch:
jobs:
  Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: update & install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y cmake
          sudo apt-get install -y git doxygen
          sudo apt-get install -y python3 python3-pip
          sudo apt-get install -y ninja-build
          sudo apt-get install -y graphviz pkg-config
          sudo apt-get install -y dos2unix
          sudo apt-get install -y cmake-format
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check folder
        run: ls
      - name: Configure
        run: make config-ubuntu
      - name: Format
        run: cmake --build --preset=ubuntu-format
      - name: Docs
        run: cmake --build --preset=ubuntu-document
      - name: Install
        run: cmake --build --preset=ubuntu-install
      - name: Test
        run: ctest --preset=ubuntu
