name: Test on Ubuntu
on:
  workflow_dispatch:
jobs:
  Configuration:
    runs-on: ubuntu-latest
    container:
      image: duyleduc520/mysfmlapp:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Project
        uses: threeal/cmake-action@main
        with:
          args: |
            --graphviz=docs/graph/graph.dot
            --no-warn-unused-cli
            -DCMAKE_BUILD_TYPE=release
          build-args: |
            -j6
            --config release
            --target all

          
