name: Test on Ubuntu
on:
  workflow_dispatch:
jobs:
  Configuration:
    runs-on: ubuntu-latest
    container:
      image: duyleduc520/mysfmlapp:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build mongocxx-driver
        run: make mongo-gcc
      - name: Configure Project
        run: make configure PRESET=ubuntu
      - name: Build Project
        run: cmake --build --preset=ubuntu
          
