name: Test on Windows
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
  push:
    branches: [dev*]
    
jobs:
  Configuration:
    runs-on: windows-latest
    steps:
      - name: install graphviz
        run: choco install graphviz
      - name: install ninja
        run: choco install ninja
      - name: install make
        run: choco install make
      - name: install dos2unix
        run: choco install dos2unix
      - name: install doxygen
        run: choco install doxygen.portable
      - name: install cmake-format
        run: |
          pip install cmake-format
          pip install PyYAML
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check folder
        run: ls
      - name: Configure
        run: make config-win
      - name: Format
        run: cmake --build --preset=windows-format
      - name: Docs
        run: cmake --build --preset=windows-document
      - name: Install
        run: cmake --build --preset=windows-install
      - name: Test
        run: ctest --preset=windows
