name: Test on Windows
on:
  push:
    branches: [dev*]
  workflow_dispatch:
    
jobs:
  Configuration:
    runs-on: windows-latest
    steps:
      - name: install graphviz
        run: choco install graphviz
      - name: install ninja
        run: choco install ninja
      - name: install make
        run: choco install make
      - name: install dos2unix
        run: choco install dos2unix
      - name: install doxygen
        run: choco install doxygen.portable
      - name: install cmake-format
        run: |
          pip install cmake-format
          pip install PyYAML
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check folder
        run: ls
      - name: Configure
        run: make config-win
      - name: Format
        run: cmake --build --preset=windows-format
      - name: Docs
        run: cmake --build --preset=windows-document
      - name: Install
        run: cmake --build --preset=windows-install
      - name: Test
        run: ctest --preset=windows
